### ISSUE TITLE
Fails at the 8080 port check

### ISSUE THREAD

**Issue by tscolari** [githubixx/ansible-role-kubernetes-controller#11]
Hey there, I've updated my cluster recently and it seems to get stuck on this:

```
- name: Wait for kube-apiserver to listen on port 8080 on the host
  wait_for:
    port: 8080
    delay: 5
    host: "{{hostvars[inventory_hostname]['ansible_' + k8s_interface].ipv4.address}}"
  run_once: true
  delegate_to: "{{groups.k8s_controller|first}}"
```

I wonder if this has anything to do with 

```
removed deprecated kube-apiserver parameter insecure-bind-address (see: #59018)
``` 

from your blog post changelog.
kube-apiserver seems to be binding :8080 to localhost for me, so this check is never successful.
